# Chapter 7

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [8]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [9]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [10]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [11]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
   ....:                      [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [19]:
data[4]=np.nan

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [23]:
df.iloc[:4, 1] = np.nan

In [24]:
df.iloc[:2, 2] = np.nan

In [25]:
df

0         1         2
0 -0.267158       NaN       NaN
1 -0.740720       NaN       NaN
2 -0.134750       NaN -1.409672
3  0.004227       NaN -0.431049
4  0.125846  1.609841  1.306120
5  1.269335  0.635382  0.021147
6  0.663857 -0.054925  1.451014

In [26]:
df.dropna()

0         1         2
4  0.125846  1.609841  1.306120
5  1.269335  0.635382  0.021147
6  0.663857 -0.054925  1.451014

In [27]:
df.dropna(thresh=2)

0         1         2
2 -0.134750       NaN -1.409672
3  0.004227       NaN -0.431049
4  0.125846  1.609841  1.306120
5  1.269335  0.635382  0.021147
6  0.663857 -0.054925  1.451014

In [28]:
df.fillna(0)

0         1         2
0 -0.267158  0.000000  0.000000
1 -0.740720  0.000000  0.000000
2 -0.134750  0.000000 -1.409672
3  0.004227  0.000000 -0.431049
4  0.125846  1.609841  1.306120
5  1.269335  0.635382  0.021147
6  0.663857 -0.054925  1.451014

In [29]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.267158  0.500000  0.000000
1 -0.740720  0.500000  0.000000
2 -0.134750  0.500000 -1.409672
3  0.004227  0.500000 -0.431049
4  0.125846  1.609841  1.306120
5  1.269335  0.635382  0.021147
6  0.663857 -0.054925  1.451014

In [30]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [31]:
df.iloc[2:, 1] = np.nan

In [32]:
df.iloc[4:, 2] = np.nan

In [33]:
df

0         1         2
0  1.086637 -0.086513 -0.300230
1  1.059860  0.520086  0.637502
2  0.470437       NaN  0.267855
3  0.401826       NaN  0.015751
4 -0.526570       NaN       NaN
5  0.059212       NaN       NaN

In [34]:
df.fillna(method="ffill")

0         1         2
0  1.086637 -0.086513 -0.300230
1  1.059860  0.520086  0.637502
2  0.470437  0.520086  0.267855
3  0.401826  0.520086  0.015751
4 -0.526570  0.520086  0.015751
5  0.059212  0.520086  0.015751

In [35]:
df.fillna(method="ffill", limit=2)

0         1         2
0  1.086637 -0.086513 -0.300230
1  1.059860  0.520086  0.637502
2  0.470437  0.520086  0.267855
3  0.401826  0.520086  0.015751
4 -0.526570       NaN  0.015751
5  0.059212       NaN  0.015751

In [36]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [38]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
   ....:                      "k2": [1, 1, 2, 3, 3, 4, 4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data["v1"] = range(7)

In [43]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [46]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [47]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
   ....:                               "pastrami", "corned beef", "bacon",
   ....:                               "pastrami", "honey ham", "nova lox"],
   ....:                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [48]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [49]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [50]:
data["animal"] = data["food"].map(meat_to_animal)

In [51]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [52]:
def get_animal(x):
   ....:     return meat_to_animal[x]

In [53]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [54]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [58]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=["Ohio", "Colorado", "New York"],
   ....:                     columns=["one", "two", "three", "four"])

In [61]:
def transform(x):
   ....:     return x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [63]:
data.index = data.index.map(transform)

In [64]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [65]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [66]:
data.rename(index={"OHIO": "INDIANA"},
   ....:             columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [67]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [68]:
bins = [18, 25, 35, 60, 100]

In [69]:
age_categories = pd.cut(ages, bins)

In [70]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [71]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [72]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [73]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [74]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [75]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [76]:
data = np.random.uniform(size=20)

In [77]:
pd.cut(data, 4, precision=2)

[(0.05, 0.28], (0.52, 0.75], (0.75, 0.98], (0.75, 0.98], (0.28, 0.52], ..., (0.75, 0.98], (0.75, 0.98], (0.28, 0.52], (0.28, 0.52], (0.75, 0.98]]
Length: 20
Categories (4, interval[float64, right]): [(0.05, 0.28] < (0.28, 0.52] < (0.52, 0.75] < (0.75, 0.98]]

In [78]:
data = np.random.standard_normal(1000)

In [79]:
quartiles = pd.qcut(data, 4, precision=2)

In [80]:
quartiles

[(-0.66, 0.04], (0.7, 2.95], (-3.86, -0.66], (-0.66, 0.04], (-0.66, 0.04], ..., (0.04, 0.7], (0.04, 0.7], (0.7, 2.95], (-0.66, 0.04], (0.7, 2.95]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.86, -0.66] < (-0.66, 0.04] < (0.04, 0.7] < (0.7, 2.95]]

In [81]:
pd.value_counts(quartiles)

(-3.86, -0.66]    250
(-0.66, 0.04]     250
(0.04, 0.7]       250
(0.7, 2.95]       250
Name: count, dtype: int64

In [82]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.8489999999999998, -1.272]    100
(-1.272, 0.0401]                 400
(0.0401, 1.232]                  400
(1.232, 2.953]                   100
Name: count, dtype: int64

In [83]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [84]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002709    -0.035666     0.042113    -0.025254
std       1.004169     1.012616     0.961066     1.026818
min      -4.026931    -3.253906    -3.038824    -3.103106
25%      -0.652693    -0.739758    -0.612471    -0.718017
50%       0.002449    -0.064429     0.050331    -0.028034
75%       0.637503     0.611126     0.708911     0.674737
max       2.672275     2.955336     3.089373     3.227327

In [85]:
col=data[2]

In [86]:
col[col.abs()>3]

760   -3.038824
979    3.089373
Name: 2, dtype: float64

In [87]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
142  1.974116  0.560294 -0.159642  3.227327
268 -4.026931  0.229095 -0.043353 -1.287346
335  1.748792 -3.253906  0.256136 -1.105000
408  0.452992  1.172618  1.180364 -3.042490
707  1.463745 -0.147223  0.841585 -3.103106
760  0.361945 -0.593642 -3.038824 -0.357701
795 -1.096739 -3.237180  0.738221  0.392040
799  0.419670 -3.169798  1.102030 -1.343954
975 -3.058442 -0.038554  1.631243  0.008722
979  1.222974 -0.735222  3.089373 -1.540186

In [88]:
data[data.abs() > 3] = np.sign(data) * 3

In [89]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.001624    -0.035005     0.042063    -0.025336
std       1.000391     1.010603     0.960663     1.025693
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.652693    -0.739758    -0.612471    -0.718017
50%       0.002449    -0.064429     0.050331    -0.028034
75%       0.637503     0.611126     0.708911     0.674737
max       2.672275     2.955336     3.000000     3.000000

In [90]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0  1.0
1  1.0 -1.0  1.0 -1.0
2 -1.0 -1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4  1.0  1.0 -1.0  1.0

In [91]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [92]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [93]:
sampler = np.random.permutation(5)

In [94]:
sampler

array([3, 4, 2, 1, 0])

In [95]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [96]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [97]:
column_sampler = np.random.permutation(7)

In [98]:
column_sampler

array([1, 4, 2, 0, 3, 5, 6])

In [99]:
df.take(column_sampler, axis="columns")

1   4   2   0   3   5   6
0   1   4   2   0   3   5   6
1   8  11   9   7  10  12  13
2  15  18  16  14  17  19  20
3  22  25  23  21  24  26  27
4  29  32  30  28  31  33  34

In [100]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [101]:
choices = pd.Series([5, 7, -1, 6, 4])

In [102]:
choices.sample(n=10, replace=True)

4    4
2   -1
1    7
2   -1
2   -1
3    6
1    7
2   -1
3    6
2   -1
dtype: int64

In [103]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
   .....:                    "data1": range(6)})

In [104]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [105]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [106]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [107]:
df_with_dummy = df[["data1"]].join(dummies)

In [108]:
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [109]:
mnames = ["movie_id", "title", "genres"]

In [110]:
#movies = pd.read_table("datasets/movielens/movies.dat", sep="::",header=None, names=mnames, engine="python")

In [111]:
np.random.seed(12345)

In [112]:
values = np.random.uniform(size=10)

In [113]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [114]:
pd.get_dummies(pd.cut(values, bins))

(18, 25]  (25, 35]  (35, 60]  (60, 100]
0     False     False     False      False
1     False     False     False      False
2     False     False     False      False
3     False     False     False      False
4     False     False     False      False
5     False     False     False      False
6     False     False     False      False
7     False     False     False      False
8     False     False     False      False
9     False     False     False      False

In [115]:
s = pd.Series([1, 2, 3, None])

In [116]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [117]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [118]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [120]:
s.dtype

Int64Dtype()

In [121]:
s[3]

<NA>

In [122]:
s[3] is pd.NA

True

In [123]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [124]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [125]:
df = pd.DataFrame({"A": [1, 2, None, 4],
   .....:                    "B": ["one", "two", "three", None],
   .....:                    "C": [False, None, False, True]})

In [126]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [127]:
df["A"] = df["A"].astype("Int64")

In [128]:
df["B"] = df["B"].astype("string")

In [129]:
df["C"] = df["C"].astype("boolean")

In [130]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [131]:
val = "a,b,  guido"

In [132]:
val.split(",")

['a', 'b', '  guido']

In [135]:
pieces = [x.strip() for x in val.split(",")]

In [136]:
pieces

['a', 'b', 'guido']

In [137]:
first, second, third = pieces

In [138]:
first + "::" + second + "::" + third

'a::b::guido'

In [139]:
"::".join(pieces)

'a::b::guido'

In [140]:
"guido" in val

True

In [141]:
val.index(",")

1

In [142]:
val.find(":")

-1

In [144]:
val.count(",")

2

In [145]:
val.replace(",", "::")

'a::b::  guido'

In [146]:
val.replace(",", "")

'ab  guido'

In [147]:
import re

In [148]:
text = "foo    bar\t baz  \tqux"

In [149]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [150]:
regex = re.compile(r"\s+")

In [151]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [152]:
regex.findall(text)

['    ', '\t ', '  \t']

In [153]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [154]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [156]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [157]:
m = regex.search(text)

In [158]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [159]:
text[m.start():m.end()]

'dave@google.com'

In [160]:
print(regex.match(text))

None


In [161]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [162]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [163]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [164]:
m.groups()

()

In [165]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [166]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [167]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
   .....:         "Rob": "rob@gmail.com", "Wes": np.nan}

In [168]:
data = pd.Series(data)

In [169]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [170]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [172]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [173]:
data_as_string_ext = data.astype('string')

In [174]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [175]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [176]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [177]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [178]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [179]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [180]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [181]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [182]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [183]:
values = pd.Series(['apple', 'orange', 'apple',
   .....:                     'apple'] * 2)

In [184]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [186]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [187]:
pd.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [188]:
values = pd.Series([0, 1, 0, 0] * 2)

In [189]:
dim = pd.Series(['apple', 'orange'])

In [190]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [191]:
dim

0     apple
1    orange
dtype: object

In [192]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [195]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [196]:
N = len(fruits)

In [197]:
rng = np.random.default_rng(seed=12345)

In [198]:
df = pd.DataFrame({'fruit': fruits,
   .....:                    'basket_id': np.arange(N),
   .....:                    'count': rng.integers(3, 15, size=N),
   .....:                    'weight': rng.uniform(0, 4, size=N)},
   .....:                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [199]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [200]:
fruit_cat = df['fruit'].astype('category')

In [201]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [202]:
c = fruit_cat.array

In [203]:
type(c)

pandas.core.arrays.categorical.Categorical

In [204]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [205]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [206]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [207]:
df['fruit'] = df['fruit'].astype('category')

In [208]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [209]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [210]:
categories = ['foo', 'bar', 'baz']

In [214]:
codes = [0,1,2,0,0,1]

In [215]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [217]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [218]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
   .....:                                         ordered=True)

In [220]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [221]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [222]:
rng = np.random.default_rng(seed=12345)

In [223]:
draws = rng.standard_normal(1000)

In [225]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [226]:
bins = pd.qcut(draws, 4)

In [227]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [228]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [229]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [230]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [232]:
bins = pd.Series(bins, name='quartile')

In [233]:
results = (pd.Series(draws)
   .....:            .groupby(bins)
   .....:            .agg(['count', 'min', 'max'])
   .....:            .reset_index())

In [234]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [235]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [236]:
N = 10_000_000

In [237]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [238]:
categories = labels.astype('category')

In [239]:
labels.memory_usage(deep=True)

600000132

In [240]:
categories.memory_usage(deep=True)

10000544

In [241]:
%time _ = labels.astype('category')

CPU times: user 224 ms, sys: 22.8 ms, total: 247 ms
Wall time: 248 ms


In [242]:
%timeit labels.value_counts()

191 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [243]:
%timeit categories.value_counts()

31.7 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [244]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [245]:
cat_s = s.astype('category')

In [246]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [247]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [248]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [249]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [250]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [251]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [252]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [253]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [254]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [255]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [256]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [257]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [258]:
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True

In [ ]:
s